# 🐼 Pandas Assignment (Class 1 & 2)

### Topics Covered
- Importing Pandas
- Series
- DataFrame
- DataFrame Creation
- head(), tail(), info(), describe()
- Column Selection
- loc & iloc
- index, columns, values
- rename()
- set_index()

**Instructions:** Solve every question in the code cell below it.

## Q1. Import the **pandas** library using the alias `pd`.

In [ ]:
# Write your answer here
import pandas as pd

## Q2. Create a **Series** containing: 10, 20, 30, 40, 50.

In [ ]:
# Write your answer here
a = pd.Series([10,20,30,40,50])
print(a)

0    10
1    20
2    30
3    40
4    50
dtype: int64

## Q3. Create a DataFrame having columns **Name**, **Age**, and **City** with at least 5 records.

In [ ]:
# Write your answer here
a = {'Name':['riya','sonam','ambika','siddhi','riddhi'],
     'Age':[20,12,16,18,19],'City':['bhopal','sagar','mumbai','riva','indore']

}

b = pd.DataFrame(a)
print(b)

     Name  Age    City
0    riya   20  bhopal
1   sonam   12   sagar
2  ambika   16  mumbai
3  siddhi   18    riva
4  riddhi   19  indore

## Q4. Create a DataFrame using a NumPy array of your choice.

In [ ]:
# Write your answer here
import numpy as np
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(pd.DataFrame(a))

   0  1  2
0  1  2  3
1  4  5  6
2  7  8  9

## Q5. Display the first **3 rows** of a DataFrame using `head()`.

In [ ]:
# Write your answer here
a = {'Name':['riya','sonam','ambika','siddhi','riddhi'],
     'Age':[20,12,16,18,19],'City':['bhopal','sagar','mumbai','riva','indore']

}

b = pd.DataFrame(a)
print(b)
b.head(3)

     Name  Age    City
0    riya   20  bhopal
1   sonam   12   sagar
2  ambika   16  mumbai
3  siddhi   18    riva
4  riddhi   19  indore

     Name  Age    City
0    riya   20  bhopal
1   sonam   12   sagar
2  ambika   16  mumbai

## Q6. Display the last **2 rows** using `tail()`.

In [ ]:
# Write your answer here
b.tail(2)

     Name  Age    City
3  siddhi   18    riva
4  riddhi   19  indore

## Q7. Display the information of a DataFrame using `info()`.

In [ ]:
# Write your answer here
b.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    5 non-null      object
 1   Age     5 non-null      int64
 2   City    5 non-null      object
dtypes: int64(1), object(2)
memory usage: 252.0+ bytes

## Q8. Display the statistical summary using `describe()`.

In [ ]:
# Write your answer here
b.describe()

             Age
count   5.000000
mean   17.000000
std     3.162278
min    12.000000
25%    16.000000
50%    18.000000
75%    19.000000
max    20.000000

## Q9. Select only the **Name** column.

In [ ]:
# Write your answer here
b['Name']

0      riya
1     sonam
2    ambika
3    siddhi
4    riddhi
Name: Name, dtype: object

## Q10. Select the **Name** and **Age** columns together.

In [ ]:
# Write your answer here
b[['Name','Age']]

     Name  Age
0    riya   20
1   sonam   12
2  ambika   16
3  siddhi   18
4  riddhi   19

## Q11. Using `loc`, print the first three rows.

In [ ]:
# Write your answer here
b.loc[0:2]

     Name  Age    City
0    riya   20  bhopal
1   sonam   12   sagar
2  ambika   16  mumbai

## Q12. Using `iloc`, print rows 1 to 3 and the first two columns.

In [ ]:
# Write your answer here
b.iloc[1:4,0:2]

     Name  Age
1   sonam   12
2  ambika   16
3  siddhi   18

## Q13. Print the DataFrame's `index`, `columns`, and `values`.

In [ ]:
# Write your answer here
b.index
b.columns
b.values

array([['riya', 20, 'bhopal'],
       ['sonam', 12, 'sagar'],
       ['ambika', 16, 'mumbai'],
       ['siddhi', 18, 'riva'],
       ['riddhi', 19, 'indore']], dtype=object)

## Q14. Rename the column **Name** to **Student_Name**.

In [ ]:
# Write your answer here
b.rename(columns={'Name': "Student_Name"}, inplace = False)

  Student_Name  Age    City
0         riya   20  bhopal
1        sonam   12   sagar
2       ambika   16  mumbai
3       siddhi   18    riva
4       riddhi   19  indore

## Q15. Set the **Name** column as the index of the DataFrame.

In [41]:
a = {'Name':['riya','sonam','ambika','siddhi','riddhi'],
     'Age':[20,12,16,18,19],'City':['bhopal','sagar','mumbai','riva','indore']

}

b = pd.DataFrame(a)
print(b)
b.set_index('Name')

     Name  Age    City
0    riya   20  bhopal
1   sonam   12   sagar
2  ambika   16  mumbai
3  siddhi   18    riva
4  riddhi   19  indore

        Age    City
Name
riya     20  bhopal
sonam    12   sagar
ambika   16  mumbai
siddhi   18    riva
riddhi   19  indore