# 🐼 Pandas Mixed Assignment (Class 1-4)

Complete all the questions using Pandas.

In [1]:
import pandas as pd
import numpy as np

data = {
    "Name": ["Aman","Neha","Ravi","Priya","Karan","Neha","Rohit","Simran"],
    "Age": [20,21,np.nan,22,20,21,23,22],
    "City": ["Delhi","Mumbai","Pune","Indore","Delhi","Mumbai","Pune","Delhi"],
    "Marks": [85,92,78,np.nan,95,92,88,90],
    "Course": ["Python","Data Analyst","Python","AI","Data Analyst","Data Analyst","AI","Python"]
}

df = pd.DataFrame(data)
df

     Name   Age    City  Marks        Course
0    Aman  20.0   Delhi   85.0        Python
1    Neha  21.0  Mumbai   92.0  Data Analyst
2    Ravi   NaN    Pune   78.0        Python
3   Priya  22.0  Indore    NaN            AI
4   Karan  20.0   Delhi   95.0  Data Analyst
5    Neha  21.0  Mumbai   92.0  Data Analyst
6   Rohit  23.0    Pune   88.0            AI
7  Simran  22.0   Delhi   90.0        Python

### Q1. Display the first 5 rows of the DataFrame.

In [2]:
# Write your code here
df.head(5)

    Name   Age    City  Marks        Course
0   Aman  20.0   Delhi   85.0        Python
1   Neha  21.0  Mumbai   92.0  Data Analyst
2   Ravi   NaN    Pune   78.0        Python
3  Priya  22.0  Indore    NaN            AI
4  Karan  20.0   Delhi   95.0  Data Analyst

### Q2. Display the last 3 rows of the DataFrame.

In [3]:
# Write your code here
df.tail(3)

     Name   Age    City  Marks        Course
5    Neha  21.0  Mumbai   92.0  Data Analyst
6   Rohit  23.0    Pune   88.0            AI
7  Simran  22.0   Delhi   90.0        Python

### Q3. Print all column names.

In [10]:
# Write your code here
df[["Name" , "Age" ,"City", "Marks", "Course"]]

df.columns

Index(['Name', 'Age', 'City', 'Marks', 'Course'], dtype='object')

### Q4. Print the shape of the DataFrame.

In [9]:
# Write your code here
df.shape

(8, 5)

### Q5. Display only the Name and Marks columns.

In [11]:
# Write your code here
df[["Name", "Marks"]]

     Name  Marks
0    Aman   85.0
1    Neha   92.0
2    Ravi   78.0
3   Priya    NaN
4   Karan   95.0
5    Neha   92.0
6   Rohit   88.0
7  Simran   90.0

### Q6. Display only the Age column.

In [12]:
# Write your code here
df[['Age']]

    Age
0  20.0
1  21.0
2   NaN
3  22.0
4  20.0
5  21.0
6  23.0
7  22.0

### Q7. Display students whose Marks are greater than 90.

In [14]:
# Write your code here
df[df['Marks'] > 90]

    Name   Age    City  Marks        Course
1   Neha  21.0  Mumbai   92.0  Data Analyst
4  Karan  20.0   Delhi   95.0  Data Analyst
5   Neha  21.0  Mumbai   92.0  Data Analyst

### Q8. Display students whose City is Delhi.

In [18]:
# Write your code here
df[df['City'] == "Delhi"]

     Name   Age   City  Marks        Course
0    Aman  20.0  Delhi   85.0        Python
4   Karan  20.0  Delhi   95.0  Data Analyst
7  Simran  22.0  Delhi   90.0        Python

### Q9. Display students whose Age is greater than 20.

In [19]:
# Write your code here
df[df['Age'] >20 ]

     Name   Age    City  Marks        Course
1    Neha  21.0  Mumbai   92.0  Data Analyst
3   Priya  22.0  Indore    NaN            AI
5    Neha  21.0  Mumbai   92.0  Data Analyst
6   Rohit  23.0    Pune   88.0            AI
7  Simran  22.0   Delhi   90.0        Python

### Q10. Display students whose Course is Python.

In [20]:
# Write your code here
df[df['Course'] == "Python"]

     Name   Age   City  Marks  Course
0    Aman  20.0  Delhi   85.0  Python
2    Ravi   NaN   Pune   78.0  Python
7  Simran  22.0  Delhi   90.0  Python

### Q11. Display students whose Course is Data Analyst and City is Mumbai.

In [21]:
# Write your code here
df[(df["Course"] == "Data Analyst") & (df["City"] == "Mumbai")]

   Name   Age    City  Marks        Course
1  Neha  21.0  Mumbai   92.0  Data Analyst
5  Neha  21.0  Mumbai   92.0  Data Analyst

### Q12. Find the total number of missing values in each column.

In [22]:
# Write your code here
df.isnull().sum()

Name      0
Age       1
City      0
Marks     1
Course    0
dtype: int64

### Q13. Fill missing values of Age with 20.

In [24]:
# Write your code here
df['Age'].fillna(20)

0    20.0
1    21.0
2    20.0
3    22.0
4    20.0
5    21.0
6    23.0
7    22.0
Name: Age, dtype: float64

### Q14. Fill missing values of Marks using the column mean.

In [28]:
# Write your code here
df["Marks"] = df["Marks"].fillna(df["Marks"].mean())
df

     Name   Age    City      Marks        Course
0    Aman  20.0   Delhi  85.000000        Python
1    Neha  21.0  Mumbai  92.000000  Data Analyst
2    Ravi  20.0    Pune  78.000000        Python
3   Priya  22.0  Indore  88.571429            AI
4   Karan  20.0   Delhi  95.000000  Data Analyst
5    Neha  21.0  Mumbai  92.000000  Data Analyst
6   Rohit  23.0    Pune  88.000000            AI
7  Simran  22.0   Delhi  90.000000        Python

### Q15. Remove duplicate rows.

In [29]:
# Write your code here
df.drop_duplicates()

     Name   Age    City      Marks        Course
0    Aman  20.0   Delhi  85.000000        Python
1    Neha  21.0  Mumbai  92.000000  Data Analyst
2    Ravi  20.0    Pune  78.000000        Python
3   Priya  22.0  Indore  88.571429            AI
4   Karan  20.0   Delhi  95.000000  Data Analyst
6   Rohit  23.0    Pune  88.000000            AI
7  Simran  22.0   Delhi  90.000000        Python

### Q16. Rename the column Marks to Score.

In [30]:
# Write your code here
df.rename(columns = {"Marks" : "Score"})

     Name   Age    City      Score        Course
0    Aman  20.0   Delhi  85.000000        Python
1    Neha  21.0  Mumbai  92.000000  Data Analyst
2    Ravi  20.0    Pune  78.000000        Python
3   Priya  22.0  Indore  88.571429            AI
4   Karan  20.0   Delhi  95.000000  Data Analyst
5    Neha  21.0  Mumbai  92.000000  Data Analyst
6   Rohit  23.0    Pune  88.000000            AI
7  Simran  22.0   Delhi  90.000000        Python

### Q17. Display students whose names start with 'N'.

In [32]:
# Write your code here
df[df["Name"].str.startswith("N")]

   Name   Age    City  Marks        Course
1  Neha  21.0  Mumbai   92.0  Data Analyst
5  Neha  21.0  Mumbai   92.0  Data Analyst

### Q18. Display students whose City is either Delhi or Pune.

In [33]:
# Write your code here
df[(df["City"] == "Delhi") |(df["City"] == "Pune")]

     Name   Age   City  Marks        Course
0    Aman  20.0  Delhi   85.0        Python
2    Ravi  20.0   Pune   78.0        Python
4   Karan  20.0  Delhi   95.0  Data Analyst
6   Rohit  23.0   Pune   88.0            AI
7  Simran  22.0  Delhi   90.0        Python

### Q19. Count how many students belong to each City.

In [34]:
# Write your code here
df["City"].value_counts()

City
Delhi     3
Mumbai    2
Pune      2
Indore    1
Name: count, dtype: int64

### Q20. Display students whose Marks are between 80 and 95.

In [42]:
# # Write your code here
df[(df["Marks"] >= 80) | (df["Marks"] >=95)]

     Name   Age    City      Marks        Course
0    Aman  20.0   Delhi  85.000000        Python
1    Neha  21.0  Mumbai  92.000000  Data Analyst
3   Priya  22.0  Indore  88.571429            AI
4   Karan  20.0   Delhi  95.000000  Data Analyst
5    Neha  21.0  Mumbai  92.000000  Data Analyst
6   Rohit  23.0    Pune  88.000000            AI
7  Simran  22.0   Delhi  90.000000        Python